# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  #schedule:
  #  - cron: '22 1 * * 5'

permissions:
  contents: read

jobs:
  check-apex:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
      - uses: actions/checkout@v3
      - name: Check APEX legetz
        uses: legetz/setup-pmd@v6.48
      - run: pmd -language apex --dir . --rulesets ./pmd-rules.xml -f text
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif
